export class AvatarHelper {
	static getAllAvatars(shuffle: boolean) {
		const avatars = [
			'AirShaman',
			'Aleph',
			'Ash',
			'Avatar1',
			'Avatar2',
			'Avatar3',
			'Bernat',
			'BobFrost',
			'Bonnie1',
			'Bonnie2',
			'Cache',
			'Caligari',
			'Cassidy',
			'Catrina',
			'Centenarian',
			'Charlie7',
			'Chihiro',
			'Croc',
			'Daedalus',
			'Death',
			'DieHard',
			'Donner',
			'Dozer',
			'DrHyde',
			'Drake',
			'Duncan',
			'Elvina',
			'Etna',
			'Eva',
			'Famine',
			'Fiercehog',
			'Foxy',
			'Gerda',
			'Goodman',
			'Gronch',
			'Gunther',
			'Hag',
			'HammerTim',
			'Hector',
			'Henry',
			'HornestFreddie',
			'Ichiro',
			'Ironhand',
			'IvyXo',
			'JackFrost',
			'Jager',
			'Jeff',
			'JohnDoe',
			'Joker',
			'Jones',
			'Kai',
			'Kremer',
			'Lewis',
			'Lina',
			'Lloyd',
			'Magellan',
			'Maja',
			'Maxine',
			'Mentor',
			'Mickey',
			'Mirage',
			'Mitchell',
			'Mortus',
			'Munch',
			'NickFrost',
			'Nobuko',
			'Odegon',
			'Ortega',
			'Otherkin',
			'Owl',
			'Pestilence',
			'PsychoPete',
			'RatKing',
			'RedHot',
			'Revenant',
			'Riley',
			'Rocket',
			'Samurai',
			'Sangay',
			'ScarAB1',
			'ScarAB2',
			'Sigurd',
			'Spider',
			'Spike',
			'Stevo',
			'Surtr',
			'Tachyon',
			'Tango1',
			'Tankman',
			'TestPilot',
			'Thermite',
			'Tomasz',
			'Torben',
			'Ulrich',
			'Ulysses',
			'Uzarsky',
			'Vesuvius',
			'Vicky',
			'Wanda',
			'War',
			'WastelandBaron',
			'Wolfhound',
			'Woody',
			'Wotan',
			'Zero',
		];
		if (!shuffle) {
			return avatars;
		}
		let ind = avatars.length,
			tempVal,
			randInd;
		while (0 !== ind) {
			randInd = Math.floor(Math.random() * ind);
			ind -= 1;
			tempVal = avatars[ind];
			avatars[ind] = avatars[randInd];
			avatars[randInd] = tempVal;
		}
		return avatars;
	}
}
